<!DOCTYPE html>
<html>

<head>
    <title>Import Report - {{ now()->format('d/m/Y H:i:s') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .summary {
            margin-bottom: 30px;
        }

        .summary-box {
            display: inline-block;
            padding: 15px 30px;
            margin: 10px;
            border-radius: 5px;
        }

        .success-box {
            background-color: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }

        .error-box {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        th,
        td {
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .success-table {
            background-color: #d4edda;
        }

        .error-table {
            background-color: #f8d7da;
        }

        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Laporan Import Pembayaran</h1>
        <p>Tanggal: {{ now()->format('d F Y H:i:s') }}</p>
    </div>

    <div class="summary">
        <div class="summary-box success-box">
            <h3>Berhasil</h3>
            <h1>{{ count($results['success']) }}</h1>
        </div>
        <div class="summary-box error-box">
            <h3>Gagal</h3>
            <h1>{{ count($results['failed']) }}</h1>
        </div>
    </div>

    @if (count($results['success']) > 0)
        <h2>Data Berhasil Diimport</h2>
        <table>
            <thead class="success-table">
                <tr>
                    <th width="5%">No</th>
                    <th width="15%">NIS</th>
                    <th width="30%">Nama Santri</th>
                    <th width="20%">Nominal</th>
                    <th width="30%">No. Kwitansi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($results['success'] as $index => $item)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $item['nis'] }}</td>
                        <td>{{ $item['nama'] }}</td>
                        <td>Rp {{ number_format($item['nominal'], 0, ',', '.') }}</td>
                        <td>{{ $item['receipt'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if (count($results['failed']) > 0)
        <h2>Data Gagal Diimport</h2>
        <table>
            <thead class="error-table">
                <tr>
                    <th width="5%">No</th>
                    <th width="10%">Baris</th>
                    <th width="15%">NIS</th>
                    <th width="25%">Nama</th>
                    <th width="45%">Error</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($results['failed'] as $index => $item)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $item['row'] ?? '-' }}</td>
                        <td>{{ $item['nis'] }}</td>
                        <td>{{ $item['nama'] ?? '-' }}</td>
                        <td>{{ $item['error'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        <p>Generated by Sistem Pembayaran Santri</p>
        <p>{{ config('app.name') }} &copy; {{ date('Y') }}</p>
    </div>
</body>

</html>
